# -*- coding: utf-8 -*-
"""API_Cals_HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8bupTky4TQemfv7UZgPIDD6cwAXit0O
"""

## used this to clear my JSON file to make sure my updated code works correctly

import os

# Check if the JSON file exists
if os.path.exists('country_info.json'):
    # Delete the JSON file
    os.remove('country_info.json')
    print("cleared.")
else:
    print("data not found.")

"""Create a Python script that prompts the user to enter a country name. The script should then call a public API to retrieve information about the specified country, such as its capital and population. The goal is to demonstrate your ability to interact with APIs using Python. Reading that Data into a Dataframe and saving that into another format like JSON.

1. Use the REST Countries APILinks to an external site. for fetching country information.

2. The script should prompt the user to input a country name.

3. Make an API call to retrieve information about the entered country. You can use the examples from the site documentation IE https://restcountries.com/v3.1/name/{name}

4. Extract and display the country's capital and population.

5. Handle errors gracefully, such as invalid input or API call failures or non-existent countries.

6. Display the results to the user AND store it in a dataframe and write that out to a JSON file. If you ask for more countries, append it to the same JSON file.


"""

import requests
import pandas as pd
import os

# function to receive a country answer and use it as input
def get_country(name, df):
    answer = requests.get(f"https://restcountries.com/v3.1/name/{name}")  # Changed country_name to name
    country = answer.json()

    # Check if country data is available
    if isinstance(country, list):
        if country:
            info = country[0]
            capital = info.get('capital', 'N/A')
            population = info.get('population', 'N/A')

            print(f"Country: {name}")
            print(f"Capital: {capital}")
            print(f"Population: {population}")

            # Create DataFrame for new data
            new_data = pd.DataFrame({'Country': [name], 'Capital': [capital], 'Population': [population]})


            if os.path.exists('country_info.json'): # Checking if there is a prior JSON file and adding new data
                df_existing = pd.read_json('country_info.json')
                df = pd.concat([df_existing, new_data], ignore_index=True) #format JSON to make easier to read
            else: # if there is no prior JSON, I create one
                df = new_data

            # Write DataFrame to JSON
            df.to_json('country_info.json', orient='records', indent=4)

    else:
        print("Country not found")



# Continuously ask for country names
while True:
    name = input("Please choose a country name: \n(type done when finished) ")
    if name.lower() == 'done':
        break

    df = get_country(name, df)

with open('country_info.json', 'r') as file:
    data = file.read()
    print("JSON file contents:")
    print(data)